workspace(name = "com_github_target_xcbbuildserviceproxy_examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Toolchains

http_archive(
    name = "build_bazel_apple_support",
    sha256 = "76df040ade90836ff5543888d64616e7ba6c3a7b33b916aa3a4b68f342d1b447",
    url = "https://github.com/bazelbuild/apple_support/releases/download/0.11.0/apple_support.0.11.0.tar.gz",
)

http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "0052d452af7742c8f3a4e0929763388a66403de363775db7e90adecb2ba4944b",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz",
)

http_archive(
    name = "build_bazel_rules_swift",
    sha256 = "653e8756001616500b110fd156694de7899278bb7480aba22b2f156438a1d810",
    url = "https://github.com/bazelbuild/rules_swift/releases/download/0.22.0/rules_swift.0.22.0.tar.gz",
)

load("@build_bazel_apple_support//lib:repositories.bzl", "apple_support_dependencies")

apple_support_dependencies()

load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")

apple_rules_dependencies()

load("@build_bazel_rules_swift//swift:repositories.bzl", "swift_rules_dependencies")

swift_rules_dependencies()

load("@build_bazel_rules_swift//swift:extras.bzl", "swift_rules_extra_dependencies")

swift_rules_extra_dependencies()

# Project dependencies

local_repository(
    name = "com_github_target_xcbbuildserviceproxy",
    path = "../",
)

load("@com_github_target_xcbbuildserviceproxy//:repositories.bzl", "xcbbuildserviceproxy_dependencies")

xcbbuildserviceproxy_dependencies()

http_archive(
    name = "build_bazel_bazel",
    patches = ["build_bazel_bazel.patch"],
    sha256 = "7766edc4c3bef7f92c2c25ca76a35f15f22c0ec21d8a45de8035dc9f6b94efeb",
    strip_prefix = "bazel-3.2.0",
    urls = ["https://github.com/bazelbuild/bazel/archive/3.2.0.tar.gz"],
)
